---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.2.6
_src_path: gh:kc-workspace/asdf-plugin-template.git
addon_yaml:
    archive: false
    checksum: false
    download: true
    fetch: true
    git: true
    github: true
    gpg: false
    help: true
    install: true
    package: false
    python: false
    system: true
    tags: true
    version: true
app_desc: A simple zero-config tool to make locally trusted development certificates
app_name: mkcert
app_repo: https://github.com/FiloSottile/mkcert
app_type: standalone
app_website: https://mkcert.dev/
archive_enabled: false
checksum_enabled: false
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_require_commands: ''
download_url: https://github.com/FiloSottile/mkcert/releases/download/v{version}/mkcert-v{version}-{os}-{arch}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    mkcert: bin/mkcert
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-mkcert
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-mkcert.git
source_enabled: true
source_type: git
source_url: https://github.com/FiloSottile/mkcert.git
sys_arch_enabled: true
sys_arch_yaml:
    aarch64*: arm64
    armv5*: armv5
    armv6*: armv6
    armv7*: armv7
    i386: '386'
    i686: '386'
    powerpc64le: ppc64le
    ppc64le: ppc64le
    x86: '386'
    x86_64: amd64
sys_ext_enabled: false
sys_os_enabled: false
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
