---
## Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: f55eb93da7cfd4b3c28efd07c483fe7fada6e28e
_src_path: /Users/kamontat/Desktop/Personal/asdf-plugin-template
app_desc: A simple zero-config tool to make locally trusted development certificates
app_name: mkcert
app_repo: https://github.com/FiloSottile/mkcert
app_type: git
app_website: https://mkcert.dev/
archive_enabled: false
checksum_enabled: false
custom_addon_yaml:
    checksum: false
    download: true
    github: true
    gpg: true
    help: true
    install: true
    system: true
    tags: true
    version: true
custom_arch_enabled: true
custom_arch_yaml:
    aarch64*: arm64
    armv5*: arm
    armv6*: arm
    armv7*: arm
    x86_64: amd64
custom_bin_paths: bin
custom_non_stable_version: (-src|-dev|-latest|-stm|[-\.]rc|-alpha|-beta|[-\.]pre|-next|snapshot|master)
custom_os_enabled: false
custom_require_commands: ''
download_url: https://github.com/FiloSottile/mkcert/releases/download/v{version}/mkcert-v{version}-{os}-{arch}
gpg_enabled: false
install_map_enabled: true
install_map_method: move
install_map_yaml:
    mkcert: bin/mkcert
package_enabled: false
plugin_author: Kamontat Chantrachirathumrong
plugin_name: asdf-mkcert
plugin_org: kc-workspace
plugin_repo: https://github.com/kc-workspace/asdf-mkcert.git
source_enabled: true
source_type: git
source_url: https://github.com/FiloSottile/mkcert.git
test_cmd_args: --version
version_file_enabled: false
version_prefix: v
